### ISSUE TITLE
Error:Execution failed for task ':app:fabricGenerateResourcesDebug'.

### ISSUE THREAD

**Issue by emmjaykay** [AndroidBootstrap/android-bootstrap-site#40]
Error:Execution failed for task ':app:fabricGenerateResourcesDebug'.
> Crashlytics Developer Tools error.

This might be related to the crashalytics key. I don't have one so I set it to be blank in my gradle.properties file.

I see this when trying to sign up for a crashalytics key

![image](https://cloud.githubusercontent.com/assets/1754170/11354043/736ab0f0-91fd-11e5-9e4f-1890549bec4f.png)

It's not even really letting me see what the app's api key is.

**Comment by donnfelker** [comment]
Dan Lew shows how to get the API key without the plugin: http://blog.danlew.net/2015/02/20/setting-up-a-new-app-in-crashlytics-without-the-plugin/   You can do this or compeltely remove the crashlytics stuff. I might remove it as its causing a lot of pain it seems.
